site_name: Biblioteca para microcontroladores sAPI
pages:
- Introducci贸n: index.md
- Instalaci贸n de IDE4PLC: ide4plc-install_es.md
- Instalation of IDE4PLC: ide4plc-install_en.md
- Instalaci贸n de IDE4PLC en GNU/Linux desde el c贸digo fuente: ide4plc-linux-from-sources_es.md
- Notas de IDE4PLC v1.0.5: IDE4PLC-v1.0.5-README.md
theme: readthedocs
